version: '3'

services:
  main-app-web:
    container_name: main-app-web
    build:
      context: .
      dockerfile: ./apps/main-app/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  docs-site-web:
    container_name: doc-site-web
    build:
      context: .
      dockerfile: ./apps/doc-site/Dockerfile
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network
  ui-storybook-web:
    container_name: ui-storybook-web
    build:
      context: .
      dockerfile: ./apps/ui-storybook/Dockerfile
    restart: always
    ports:
      - 3002:6006
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
